//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBase.Dapps.CloudManager.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBase.Dapps.CloudManager.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/AddAccountPermission?accountToAdd={0}&amp;accountPublicKey={1}.
        /// </summary>
        internal static string AddPermitted {
            get {
                return ResourceManager.GetString("AddPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/AddReservedSeat.
        /// </summary>
        internal static string AddReservedSeat {
            get {
                return ResourceManager.GetString("AddReservedSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/AddStake?stake=.
        /// </summary>
        internal static string AddStake {
            get {
                return ResourceManager.GetString("AddStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/ChangeSidechainConfigurations.
        /// </summary>
        internal static string ChangeSideChainConfigurations {
            get {
                return ResourceManager.GetString("ChangeSideChainConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/ClaimStake.
        /// </summary>
        internal static string ClaimStake {
            get {
                return ResourceManager.GetString("ClaimStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/EndSidechain?endSidechain=true&amp;sidechain=.
        /// </summary>
        internal static string EndSideChain {
            get {
                return ResourceManager.GetString("EndSideChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/ExecuteQuery.
        /// </summary>
        internal static string ExecQuery {
            get {
                return ResourceManager.GetString("ExecQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/PauseSidechain.
        /// </summary>
        internal static string PauseSideChain {
            get {
                return ResourceManager.GetString("PauseSideChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Provider/DeleteSidechainFromDatabase?sidechainName={0}&amp;force={1}.
        /// </summary>
        internal static string ProducerDeleteDatabase {
            get {
                return ResourceManager.GetString("ProducerDeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/RemoveAccountFromBlacklist?account=.
        /// </summary>
        internal static string RemoveBlackList {
            get {
                return ResourceManager.GetString("RemoveBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/RemoveAccountPermission?accountToRemove=.
        /// </summary>
        internal static string RemovePermitted {
            get {
                return ResourceManager.GetString("RemovePermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/RemoveReservedSeats.
        /// </summary>
        internal static string RemoveReservedSeat {
            get {
                return ResourceManager.GetString("RemoveReservedSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/CheckRequesterConfig.
        /// </summary>
        internal static string RequesterConfig {
            get {
                return ResourceManager.GetString("RequesterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/CheckCurrentStakeInSidechain.
        /// </summary>
        internal static string RequesterStake {
            get {
                return ResourceManager.GetString("RequesterStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/CheckSidechainReservedSeats.
        /// </summary>
        internal static string ReservedSeats {
            get {
                return ResourceManager.GetString("ReservedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/RunSidechainMaintenance.
        /// </summary>
        internal static string ResumeSideChain {
            get {
                return ResourceManager.GetString("ResumeSideChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Network/GetSidechainState?sidechainName=.
        /// </summary>
        internal static string SidechainState {
            get {
                return ResourceManager.GetString("SidechainState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/SignQuery.
        /// </summary>
        internal static string SignQuery {
            get {
                return ResourceManager.GetString("SignQuery", resourceCulture);
            }
        }
    }
}
